Issue Context manager
BaboucheOne/BuggyBot pull request #12
Opened 2024-05-07 16:34 UTC by EctobiusRexV

This makes it so that we can specify if we<re in production or in developpement mode. you will have to make 2 different .env files which are .env.prod and .env.dev for it to work. Then, when launching the program, specify the environnement by using the argument --env prod or --env dev.  By default, the environnemnt is set to production mode.

2024-05-07 21:52 UTC, BaboucheOne requested changes
Ok ok! Tout d'abord, j'apprécie l'idée d'avoir pensé à créer deux fichiers .env, un pour la production et un pour le développement. Cela peut vraiment nous être utile. De plus, la gestion des arguments est bien réalisée, parfait !

Cependant, l'utilisation d'un gestionnaire de contexte est un peu plus complexe. En réalité, ce qui se cache derrière un gestionnaire de contexte est un Service Locator (https://stackify.com/service-locator-pattern/).

Un service locator est un objet qui permet l'injection de dépendances. En fait, tout ce que notre contexte fait, c'est créer les objets de l'application qui seront modulables (comme le repository, le service) et les ajouter dans un service locator.

En réalité, nous n'avons pas un mais deux contextes. Un pour la production et un pour le développement. Les deux auront sensiblement le même code, seule la configuration pour construire nos objets changera.

Mettre en place un Service Locator avec la création de contextes est quand même un gros morceau à traiter ! Je te suggère de te renseigner d'abord sur la manière de réaliser un service locator en Python, puis d'essayer de mettre en place le contexte (tu verras, c'est bien plus simple).

Si jamais tu as besoin d'aide, je prendrai le temps de t'expliquer les choses !

2024-05-12 22:37 UTC, EctobiusRexV commented
Je viens de push mes premier changements sur cet issue... J'aimerais savoir si ça a du sens avant de compléter le tout.

2024-05-16 23:50 UTC, Marc786 commented on bot/config/service_locator.py
> +        cls.__dependencies.clear()
J'ai une impression de déjà vue @BaboucheOne 🤔

2024-05-16 23:50 UTC, Marc786 commented on bot/config/application_context.py
> +        mongo_client = self.__create_mongo_client()
Tu veux pas instancier ton Mongo client ici, car tu veux que ca reste de la logique caché dans tes sous contextes

2024-05-17 20:11 UTC, BaboucheOne commented on bot/config/service_locator.py
> +        cls.__dependencies.clear()
hahah, c'est un service locator comme un autre @Marc786 :eyes:

2024-05-17 20:12 UTC, BaboucheOne commented on bot/config/application_context.py
> +        mongo_client = self.__create_mongo_client()
J'ai pas tant compris. Est-ce que tu dis qu'il faudrait mettre une méthode qui s'occupe de la création du client dans les contextes en non dans la base classe ?

2024-05-17 20:14 UTC, Marc786 commented on bot/config/application_context.py
> +        mongo_client = self.__create_mongo_client()
ouais genre

2024-05-20 01:53 UTC, BaboucheOne commented on bot/config/service_locator.py
> +        cls.__dependencies.clear()
Je pourrais en mettre un mais ne pas autoriser le replace car a date cela nous sert a rien

2024-05-20 19:26 UTC, merged